import { rootDir, storageDir } from './paths';

export const config = {
  env: process.env.NODE_ENV || 'development',
  port: Number(process.env.PORT || 8787),
  workerPollIntervalMs: Number(process.env.WORKER_POLL_INTERVAL_MS || 1200),
  webOrigin: process.env.WEB_ORIGIN || 'http://localhost:5173',
  publicBaseUrl: process.env.PUBLIC_BASE_URL || '',
  qwenApiKey: process.env.QWEN_API_KEY || '',
  qwenBaseUrl: process.env.QWEN_BASE_URL || 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  qwenVlModel: process.env.QWEN_VL_MODEL || 'qwen-vl-plus',
  qwenTextModel: process.env.QWEN_TEXT_MODEL || 'qwen-plus',
  defaultAiProvider: (process.env.DEFAULT_AI_PROVIDER || 'qwen').toLowerCase(),
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  geminiBaseUrl: process.env.GEMINI_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta/openai',
  geminiVlModel: process.env.GEMINI_VL_MODEL || 'gemini-2.5-flash',
  geminiTextModel: process.env.GEMINI_TEXT_MODEL || 'gemini-2.5-flash',
  mockQwen: (process.env.MOCK_QWEN || 'false').toLowerCase() === 'true',
  renderCodec: process.env.RENDER_CODEC || 'h264',
  fps: Number(process.env.RENDER_FPS || 30),
  width: Number(process.env.RENDER_WIDTH || 1080),
  height: Number(process.env.RENDER_HEIGHT || 1920),
  durationSeconds: Number(process.env.RENDER_DURATION_SECONDS || 45),
  previewDurationSeconds: Number(process.env.PREVIEW_DURATION_SECONDS || 18),
  renderConcurrency: Number(process.env.RENDER_CONCURRENCY || 1),
  workerConcurrency: Number(process.env.WORKER_CONCURRENCY || 1),
  maxVersions: Number(process.env.MAX_VERSIONS || 6),
  qualityThreshold: Number(process.env.QUALITY_THRESHOLD || 82),
  autoRegenerateMax: Number(process.env.AUTO_REGENERATE_MAX || 1),
  storageDriver: process.env.STORAGE_DRIVER || 'local',
  queueDriver: process.env.QUEUE_DRIVER || 'file',
  databaseDriver: process.env.DATABASE_DRIVER || 'json',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  databaseUrl: process.env.DATABASE_URL || '',
  jwtSecret: process.env.JWT_SECRET || 'dev-change-me',
  authRequired: (process.env.AUTH_REQUIRED || 'true').toLowerCase() === 'true',
  allowAnonymous: (process.env.ALLOW_ANONYMOUS || 'false').toLowerCase() === 'true',
  storagePublicBaseUrl: process.env.STORAGE_PUBLIC_BASE_URL || '',
  s3Endpoint: process.env.S3_ENDPOINT || '',
  s3Region: process.env.S3_REGION || 'us-east-1',
  s3Bucket: process.env.S3_BUCKET || '',
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID || '',
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY || '',
  s3ForcePathStyle: (process.env.S3_FORCE_PATH_STYLE || 'true').toLowerCase() === 'true',
  rootDir,
  storageDir,
};
